### ISSUE TITLE
JSONSchemaMarkdown.js missing from npm package

### ISSUE THREAD

**Issue by s4m0r4m4** [BrianWendt/json-schema-md-doc#10]
Hello, you currently have the entire docs directory in your npm ignore, which means that JSONSchemaMarkdown.js is not actually included in the published npm package. I'll submit a PR to change that if you don't have any objections.

**Comment by BrianWendt** [comment]
@s4m0r4m4
Wow, my NPM package was all sorts of not helpful. This project got thrown together and, if I remember right, the NPM package was an afterthought. It needs further cleanup but for now I've solved this problem.
/docs/lib/JSONSchemaMarkdown.js is now available.

**Comment by s4m0r4m4** [comment]
Sounds good, I see your fix commit. You can also check out my linked PR for a different approach, either way is fine by me as long as the npm package is good.

**Comment by s4m0r4m4** [comment]
I just pulled 0.1.82 and the import now works, thanks!
I am also seeing the entire docs/lib folder in your npm package, which means jquery, index.js, and issue.js are in there, along with their respective html pages and the samples folder. I think you really just want that single JS file in a source folder with an index file that exports it. Maybe type info too so it can be used in typescript easily. I'd be happy to make any modifications to my PR if you'd like!
